# Generated by Django 3.0.7 on 2021-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payments_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_proof',
            field=models.FileField(upload_to='media'),
        ),
    ]
