# Generated by Django 3.0.7 on 2021-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20211218_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_proof',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
