# Generated by Django 3.0.7 on 2021-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20211221_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
