# Generated by Django 3.0.7 on 2021-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
